#!/bin/sh

# Cleanup old directories
rm -rf obj_dir
rm -f counter.vcd

# Run Verilator to translate Verilog into C++, including C++ testbench
# Top-level SV file should come first in cmd-line args
verilator -Wall --cc --trace f1_fsm.sv --exe f1_fsm_tb.cpp

# Build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vf1_fsm.mk Vf1_fsm

# Run executable simulation file
obj_dir/Vf1_fsm