#!/bin/sh

# Cleanup old directories
rm -rf obj_dir
rm -f counter.vcd

# Run Verilator to translate Verilog into C++, including C++ testbench
# Top-level SV file should come first in cmd-line args
verilator -Wall --cc --trace top.sv clktick.sv delay.sv f1_fsm.sv lfsr_7.sv --exe challenge_tb.cpp

# Build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vtop.mk Vtop

# Run executable simulation file
obj_dir/Vtop